# Generated by Django 6.0.3 on 2026-04-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('course_url', models.ImageField(blank=True, null=True, upload_to='course_image/')),
                ('description', models.TextField()),
                ('video_link', models.URLField(blank=True, help_text='Youtube video link', null=True)),
                ('duration', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
