# Generated by Django 6.0.3 on 2026-04-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('enrolled', 'Not Started'), ('in_progress', 'In Progress'), ('pending', 'Pending'), ('completed', 'Completed'), ('dropped', 'Dropped')], db_index=True, default='pending', max_length=50),
        ),
    ]
