# Generated by Django 6.0.3 on 2026-04-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_enrollment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('enrolled', 'Enrolled'), ('in_progress', 'In Progress'), ('pending', 'Pending'), ('completed', 'Completed'), ('dropped', 'Dropped'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=50),
        ),
    ]
