# Generated by Django 6.0.3 on 2026-04-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_role_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='textums',
            field=models.CharField(default='fazil test'),
        ),
    ]
