# Generated by Django 6.0.3 on 2026-04-06 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_textums'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='textums',
        ),
    ]
